version: "3.9"

services:
    api:
        build: ./app
        ports: 
            - 8000:8000
        environment:
            - DB_URL=mongodb://db/foondaMateDB
            - SECRET_KEY=05f8d73444f5045fd9471ca9e48bcb4162d9fa7da72cee7e5210fbc408f59f41
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60
        volumes:
            - ./app:/app
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - taskdb:/data/db
    front-end:
        build: ./front-end
        ports: 
            - 3000:3000
        volumes:
            - ./front-end:/front-end
volumes:
    taskdb:
